apiVersion: v1
kind: Secret
metadata:
  name: location-postgres-secret
  namespace: uber
type: Opaque
data:
  # Values: user / password / uberdb-locations (base64 encoded)
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: dWJlcmRiLWxvY2F0aW9ucw==
