apiVersion: v1
kind: ConfigMap
metadata:
  name: ride-service-configmap
  namespace: uber
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://ride-postgres:5432/uberdb-rides
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_RABBITMQ_HOST: rabbitmq
  FEIGN_USER_SERVICE_URL: http://user-service:8080
  FEIGN_DRIVER_SERVICE_URL: http://driver-service:8080
  FEIGN_LOCATION_SERVICE_URL: http://location-service:8080
  FEIGN_PAYMENT_SERVICE_URL: http://payment-service:8080