apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: uber
spec:
  type: NodePort        # Only NodePort in the entire cluster — all others are ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080   # Access from outside: http://$(minikube ip):30080