spring:
  application:
    name: ride-service
  datasource:
    url: jdbc:postgresql://postgres:5432/uberdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      separator: ^^
  mongodb:
    uri: mongodb://root:rootpass@mongo:27017/ubermongo?authSource=admin
  data:
    redis:
      host: redis
      port: 6379
      password: redispass
    neo4j:
      uri: bolt://neo4j:7687
      username: neo4j
      password: neo4jpass
server:
  port: 8080
jwt:
  secret: "bXlzdXBlcnNlY3JldGtleWZvcmp3dGF1dGhlbnRpY2F0aW9u"
  expiration: 86400000