apiVersion: v1
kind: Service
metadata:
  name: location-postgres
  namespace: uber
  labels:
    app: location-postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: location-postgres
