spring.application.name=location-service
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/uberdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.separator=^^
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.mongodb.uri=mongodb://root:rootpass@localhost:27017/ubermongo?authSource=admin
